"""empty message

Revision ID: d33a359c5009
Revises: 
Create Date: 2019-10-06 17:47:24.316991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33a359c5009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('download', sa.Float(), nullable=True),
    sa.Column('upload', sa.Float(), nullable=True),
    sa.Column('ping', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speed_log')
    # ### end Alembic commands ###
